### PR TITLE
Add graph for loop metrics

### PR DESCRIPTION
**Pull request by sam-github**
Depends on https://github.com/RuntimeTools/graphmetrics/pull/23 

Works much better with https://github.com/RuntimeTools/appmetrics/pull/467, because without it values are truncated to integral milliseconds,  infrequently reported, and include epoll block times along with execution times.

### CODE REVIEW

**Comment by sjanuary** [comment]
@sam-github - did we agree to remove the latency graph and replace with the new loop time graph? This PR seems to just add the new one. Screen space is limited for the dashboard so if the old graph is not that useful I'd rather just get rid of it than add scrollbars.

**Comment by sam-github** [comment]
@sjanuary I want to remove the eventloop and replace with loop, but I didn't get a thumbs up or down from anyone that I recall, so this PR just adds the missing graph.

Can I delete eventloop? If so, I'll do an rebase.

**Comment by sjanuary** [comment]
Yes, we're happy to delete the event loop chart. Confirmed with @tobespc and @stalleyj this morning.

**Comment by sam-github** [comment]
@sjanuary rebased, removed `eventloop`, PTAL

**Pull request merged**
