### PR TITLE
Add a header bar with configurable title and docs link

### PR DESCRIPTION
**Pull request by sjanuary**

### CODE REVIEW

**Comment by sjanuary** [comment]
Fixes #29

**Comment by tobespc** [comment]
lgtm

**Comment by sam-github** [comment]
didn't add docs to https://github.com/RuntimeTools/appmetrics-dash#dashmonitoroptions

**Comment by tobespc** [comment]
@sam-github @NikCanvin   Nik, we discussed whether or not to advertise this, what are your thoughts ?

**Pull request merged**
