### PR TITLE
WIP support auto-attach to HTTPS.

### PR DESCRIPTION
**Pull request by sam-github**
Mostly works, except for NodeReport, which fails in the front end after receiving the report, no idea why:

```
Uncaught TypeError: Cannot read property 'document' of null
    at n.<anonymous> (nodeReport.js:15)

```

Depends on #43, and #45  (I'll rebase them away once they merge)

### CODE REVIEW

**Comment by sam-github** [comment]
This would be nice to have as a minor release for HTTPS support, but needs a front-ender to explain why with HTTPS `window.open();` returns `null`. My googling got me nowhere.

**Comment by mattcolegate** [comment]
LGTM, http support is kept whilst https is added alongside.

**Comment by sjanuary** [comment]
Was this actually ready? WIP?

**Comment by sjanuary** [comment]
@sam-github - it works on https now apart from node report, right? If so let's open another issue to track the node report bug since this PR has been landed.

**Comment by sam-github** [comment]
Yes, works accept for node-report.

**Pull request merged**
