### PR TITLE
Remove authentication

### PR DESCRIPTION
**Pull request by sam-github**

### CODE REVIEW

**Comment by sam-github** [comment]
@corbint Travis was running this PR as ruby, once I pushed a travis config file the ci went green.

**Comment by mattcolegate** [comment]
This PR seems to be a muddle of a couple of issues - any chance it can be refactored to be several issue-specific PRs?

**Comment by sam-github** [comment]
Depends on https://github.com/RuntimeTools/appmetrics-dash/pull/15

**Comment by mattcolegate** [comment]
LGTM

**Pull request merged**
