### PR TITLE
Allow appsody apps to use socket.io

### PR DESCRIPTION
**Pull request by sam-github**
Instead of fighting over ownership of the http request event, expose the
    dashboard on the user-provided express app.
    
    server.js is modelled after the one from the appsody nodejs-express
    stack, stripped down to a minimal reproduction of the chat application
    failing.
    
    Compare to:
    
    https://github.com/appsody/stacks/blob/dc03bec53c0bfa5/incubator/nodejs-express/image/project/server.js

--
    test: chat example using pre-installed socket.io
    
    It doesn't have to use the same socket.io version as the dashboard, but
    doing so allows it to use the appmetrics-dash/node_modules, instead of
    having to do a `cd test/apps/chat-example; npm i` as a pre-test step.

--

    test: chat-example from socket.io
    
    From:
    - https://github.com/socketio/chat-example/tree/e2530b23ffc9c17c3a1a3

The first commits add the chat example from socket.io, and show that it can work with appmetrics-dashboard by avoiding `.attach()` and using `.monitor()`.

Trying that approach with the nodejs-express stack in appsody failed, so the next commits add a reproduction of the appsody failure modelled after its server.js, and modify the `monitor()` API to use the root express app rather than attempting to replace the http `'request'` event listener.

### CODE REVIEW

**Comment by sam-github** [comment]
Sorry, @tobespc, I fixed the example apps and repushed.

**Comment by sam-github** [comment]
@tobespc Tried to make codebeat happy, I assume its a prereq for merging?

**Comment by sam-github** [comment]
@tobespc @rwalle61 diff is uncovered because I moved original code (that was uncovered). Since the coverage is unrelated to this PR, can we merge this? Its blocking https://github.com/appsody/stacks/issues/447

**Comment by sam-github** [comment]
codebeat hates `onIoConnection()`, but its existing code, and I'm not sure how to make it happy.

@tobespc PTAL

**Comment by mattcolegate** [comment]
I'll have a look as Toby's not in today

**Comment by sam-github** [comment]
@mattcolegate look merge and publishable now? checks have passed.

**Comment by sam-github** [comment]
Thanks @tobespc

**Pull request merged**
